spring:
  datasource:
    driver-class-name: ${JDBC_DATABASE_DRIVER:}
    url: ${JDBC_DATABASE_URL:}
    username: ${JDBC_DATABASE_USERNAME:}
    password: ${JDBC_DATABASE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans : true
        dialect: ${SPRING_JPA_HIBERNATE_DIALECT:}
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 86400000
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            spl:
              BasicBinder : TRACE